### ISSUE TITLE
字体描边

### ISSUE THREAD

**Issue by Cynxek** [muzuiget/twosub-support#2]
现有的字体描边感觉略粗，可以考虑增加去除描边和调整描边粗细的功能。

**Comment by muzuiget** [comment]
去掉描边可以在设置页面的“基础样式”里去掉，然后自己在“主题样式”里加其它边缘效果。

不过真有必要自定义粗细吗？感觉现在样式属性的设置控件已经有点多了，再复杂得重新上自行填 CSS 代码了。

**Comment by muzuiget** [comment]
才发现我看错了项目了，这个项目已经被我废弃，虽然还能用。迁移到 Dualsub https://dualsub.netlify.app，原因是支持多个网站，又不想一个网站发一个扩展。
